// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartDriver.Persistence.Contexts;

namespace SmartDriver.Persistence.Migrations
{
    [DbContext(typeof(SmartDriverContext))]
    [Migration("20210812153742_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SmartDriver.Domain.Reserva", b =>
                {
                    b.Property<int>("num")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("condutorid")
                        .HasColumnType("int");

                    b.Property<DateTime>("dataretorno")
                        .HasColumnType("DATE");

                    b.Property<DateTime>("datasaida")
                        .HasColumnType("DATE");

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("fluig")
                        .HasColumnType("text");

                    b.Property<string>("motivo")
                        .HasColumnType("text");

                    b.Property<string>("obs")
                        .HasColumnType("text");

                    b.Property<string>("placaid")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("qtdpessoas")
                        .HasColumnType("int");

                    b.Property<string>("situacao")
                        .IsRequired()
                        .HasColumnType("ENUM('À confirmar','Confirmada')");

                    b.HasKey("num");

                    b.HasIndex("condutorid");

                    b.HasIndex("placaid");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("SmartDriver.Domain.Saida", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("combustretorno")
                        .HasColumnType("ENUM('Completo','1/2','1/4','3/4','Reserva')");

                    b.Property<string>("combustsaida")
                        .IsRequired()
                        .HasColumnType("ENUM('Completo','1/2','1/4','3/4','Reserva')");

                    b.Property<int>("condutorid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("dataretorno")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("datasaida")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("desclocalestacionado")
                        .HasColumnType("text");

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("kmretorno")
                        .HasColumnType("int");

                    b.Property<int>("kmsaida")
                        .HasColumnType("int");

                    b.Property<string>("localestacionado")
                        .HasColumnType("text");

                    b.Property<string>("obsretorno")
                        .HasColumnType("text");

                    b.Property<string>("obssaida")
                        .HasColumnType("text");

                    b.Property<string>("placaid")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("id");

                    b.HasIndex("condutorid");

                    b.HasIndex("placaid");

                    b.ToTable("Saidas");
                });

            modelBuilder.Entity("SmartDriver.Domain.Veiculo", b =>
                {
                    b.Property<string>("placa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("dpto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("km")
                        .HasColumnType("int");

                    b.Property<int?>("manutencaokm")
                        .HasColumnType("int");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("obs")
                        .HasColumnType("text");

                    b.Property<string>("rodizio")
                        .HasColumnType("ENUM('Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira')");

                    b.Property<string>("situacao")
                        .IsRequired()
                        .HasColumnType("ENUM('Disponível','Indisponível','Em Manutenção','Em Uso')");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("placa");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("SmartDriver.Domain.identity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("SmartDriver.Domain.identity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Dpto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SmartDriver.Domain.identity.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SmartDriver.Domain.identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SmartDriver.Domain.identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SmartDriver.Domain.identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SmartDriver.Domain.identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartDriver.Domain.Reserva", b =>
                {
                    b.HasOne("SmartDriver.Domain.identity.User", "User")
                        .WithMany("Reservas")
                        .HasForeignKey("condutorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartDriver.Domain.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("placaid");

                    b.Navigation("User");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SmartDriver.Domain.Saida", b =>
                {
                    b.HasOne("SmartDriver.Domain.identity.User", "User")
                        .WithMany("Saidas")
                        .HasForeignKey("condutorid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartDriver.Domain.Veiculo", "Veiculo")
                        .WithMany("Saidas")
                        .HasForeignKey("placaid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SmartDriver.Domain.identity.UserRole", b =>
                {
                    b.HasOne("SmartDriver.Domain.identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartDriver.Domain.identity.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartDriver.Domain.Veiculo", b =>
                {
                    b.Navigation("Saidas");
                });

            modelBuilder.Entity("SmartDriver.Domain.identity.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartDriver.Domain.identity.User", b =>
                {
                    b.Navigation("Reservas");

                    b.Navigation("Saidas");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
